### ISSUE TITLE
And the documentation is WHERE?

### ISSUE THREAD

**Issue by abyrvalg666** [improveTheWorld/ChatGPT-Bridge#2]
There is no WIKI available at the link. OK I have successfully installed the plugin but there is absolutely no description of how to work with it. I tried several websocket clients and they get disconnected by server or not connecting at all. Please provide docs, thank you!

**Comment by improveTheWorld** [comment]
- Use the V1.0.0_rc-1. It's a match more polished version.
- The plugin is in a client configuration , so you need to use a server that accept any connexion request at the used port. When connected , the plugin will start sending the last received message..
- Check the readme.md, it was updated to include match more informations.
- Please let me know if you still have a problem after that.
